version: '3'
services:
  mysql-development:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: project
    ports:
      - "3306:3306"
    network_mode: host
  service-sn:
    image: service-sn:latest
    ports:
      - "8080:8080"
      - "8080:8082"
    restart: on-failure
    depends_on:
      - mysql-development
    network_mode: host

networks:
  fullstack:
    driver: bridge



