// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package counter_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CounterServiceClient is the client API for CounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterServiceClient interface {
	NewMessage(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error)
	MessageRead(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error)
	CompensateNewMessage(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error)
	CompensateMessageRead(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error)
}

type counterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterServiceClient(cc grpc.ClientConnInterface) CounterServiceClient {
	return &counterServiceClient{cc}
}

func (c *counterServiceClient) NewMessage(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error) {
	out := new(CounterEventResponse)
	err := c.cc.Invoke(ctx, "/counter_api.CounterService/NewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) MessageRead(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error) {
	out := new(CounterEventResponse)
	err := c.cc.Invoke(ctx, "/counter_api.CounterService/MessageRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) CompensateNewMessage(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error) {
	out := new(CounterEventResponse)
	err := c.cc.Invoke(ctx, "/counter_api.CounterService/CompensateNewMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) CompensateMessageRead(ctx context.Context, in *CounterEventRequest, opts ...grpc.CallOption) (*CounterEventResponse, error) {
	out := new(CounterEventResponse)
	err := c.cc.Invoke(ctx, "/counter_api.CounterService/CompensateMessageRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterServiceServer is the server API for CounterService service.
// All implementations must embed UnimplementedCounterServiceServer
// for forward compatibility
type CounterServiceServer interface {
	NewMessage(context.Context, *CounterEventRequest) (*CounterEventResponse, error)
	MessageRead(context.Context, *CounterEventRequest) (*CounterEventResponse, error)
	CompensateNewMessage(context.Context, *CounterEventRequest) (*CounterEventResponse, error)
	CompensateMessageRead(context.Context, *CounterEventRequest) (*CounterEventResponse, error)
	mustEmbedUnimplementedCounterServiceServer()
}

// UnimplementedCounterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCounterServiceServer struct {
}

func (UnimplementedCounterServiceServer) NewMessage(context.Context, *CounterEventRequest) (*CounterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMessage not implemented")
}
func (UnimplementedCounterServiceServer) MessageRead(context.Context, *CounterEventRequest) (*CounterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageRead not implemented")
}
func (UnimplementedCounterServiceServer) CompensateNewMessage(context.Context, *CounterEventRequest) (*CounterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompensateNewMessage not implemented")
}
func (UnimplementedCounterServiceServer) CompensateMessageRead(context.Context, *CounterEventRequest) (*CounterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompensateMessageRead not implemented")
}
func (UnimplementedCounterServiceServer) mustEmbedUnimplementedCounterServiceServer() {}

// UnsafeCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterServiceServer will
// result in compilation errors.
type UnsafeCounterServiceServer interface {
	mustEmbedUnimplementedCounterServiceServer()
}

func RegisterCounterServiceServer(s grpc.ServiceRegistrar, srv CounterServiceServer) {
	s.RegisterService(&CounterService_ServiceDesc, srv)
}

func _CounterService_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter_api.CounterService/NewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).NewMessage(ctx, req.(*CounterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_MessageRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).MessageRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter_api.CounterService/MessageRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).MessageRead(ctx, req.(*CounterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_CompensateNewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).CompensateNewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter_api.CounterService/CompensateNewMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).CompensateNewMessage(ctx, req.(*CounterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_CompensateMessageRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).CompensateMessageRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/counter_api.CounterService/CompensateMessageRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).CompensateMessageRead(ctx, req.(*CounterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CounterService_ServiceDesc is the grpc.ServiceDesc for CounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "counter_api.CounterService",
	HandlerType: (*CounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMessage",
			Handler:    _CounterService_NewMessage_Handler,
		},
		{
			MethodName: "MessageRead",
			Handler:    _CounterService_MessageRead_Handler,
		},
		{
			MethodName: "CompensateNewMessage",
			Handler:    _CounterService_CompensateNewMessage_Handler,
		},
		{
			MethodName: "CompensateMessageRead",
			Handler:    _CounterService_CompensateMessageRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "counter.proto",
}
